@startuml
abstract class EvaluadorAbstracto {
    - EvaluadorMano siguiente
    + void setSiguiente(EvaluadorMano siguiente)
    + Mano evaluar(ArrayList<Carta> cartas)
    + abstract Mano evaluarMano(ArrayList<Carta> cartas)
}
class EvaluadorEscaleraReal extends EvaluadorAbstracto {
    + Mano evaluarMano(ArrayList<Carta> cartas)
    - boolean esColor(ArrayList<Carta> cartas)
    - boolean esEscalera(ArrayList<Carta> cartas)
    - boolean contieneAs(ArrayList<Carta> cartas)
}

class EvaluadorFull extends EvaluadorAbstracto {
    + Mano evaluarMano(ArrayList<Carta> cartas)
}



class EvaluadorPoker extends EvaluadorAbstracto {
    + Mano evaluarMano(ArrayList<Carta> cartas)
    - boolean tieneRepetidos(ArrayList<Carta> cartas, int cantidad)
}

@enduml